### ISSUE TITLE
wasm-example fails on browser runtime - `failed: local count too large`

### ISSUE THREAD

**Issue by softmarshmallow** [rust-skia/rust-skia#1158]
## Steps to reproduce
```
git clone https://github.com/rust-skia/rust-skia
cd wasm-example
make build
make serve
```

<img width="1671" alt="Image" src="https://github.com/user-attachments/assets/3957e270-07e6-402f-899e-589e06d270ea" />

logs (from browser window)
```
wasm-example.js:756 wasm streaming compile failed: CompileError: WebAssembly.instantiateStreaming(): Compiling function #48366:"skcms_private::baseline::exec_stages(skcms_priv..." failed: local count too large @+12381568
overrideMethod @ hook.js:608
(anonymous) @ wasm-example.js:756
Promise.then
(anonymous) @ wasm-example.js:751
Promise.then
instantiateAsync @ wasm-example.js:743
createWasm @ wasm-example.js:832
(anonymous) @ wasm-example.js:8638
(anonymous) @ main.js:16Understand this error
wasm-example.js:757 falling back to ArrayBuffer instantiation
overrideMethod @ hook.js:608
(anonymous) @ wasm-example.js:757
Promise.then
(anonymous) @ wasm-example.js:751
Promise.then
instantiateAsync @ wasm-example.js:743
createWasm @ wasm-example.js:832
(anonymous) @ wasm-example.js:8638
(anonymous) @ main.js:16Understand this error
wasm-example.js:719 failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): Compiling function #48366:"skcms_private::baseline::exec_stages(skcms_priv..." failed: local count too large @+12381568
overrideMethod @ hook.js:608
(anonymous) @ wasm-example.js:719
Promise.then
instantiateArrayBuffer @ wasm-example.js:718
(anonymous) @ wasm-example.js:758
Promise.then
(anonymous) @ wasm-example.js:751
Promise.then
instantiateAsync @ wasm-example.js:743
createWasm @ wasm-example.js:832
(anonymous) @ wasm-example.js:8638
(anonymous) @ main.js:16Understand this error
wasm-example.js:596 Aborted(CompileError: WebAssembly.instantiate(): Compiling function #48366:"skcms_private::baseline::exec_stages(skcms_priv..." failed: local count too large @+12381568)
overrideMethod @ hook.js:608
abort @ wasm-example.js:596
(anonymous) @ wasm-example.js:725
Promise.then
instantiateArrayBuffer @ wasm-example.js:718
(anonymous) @ wasm-example.js:758
Promise.then
(anonymous) @ wasm-example.js:751
Promise.then
instantiateAsync @ wasm-example.js:743
createWasm @ wasm-example.js:832
(anonymous) @ wasm-example.js:8638
(anonymous) @ main.js:16Understand this error
wasm-example.js:615 Uncaught (in promise) RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): Compiling function #48366:"skcms_private::baseline::exec_stages(skcms_priv..." failed: local count too large @+12381568)
    at abort (wasm-example.js:615:11)
    at wasm-example.js:725:5
```

**Comment by softmarshmallow** [comment]
Could not identify the issue, gave up fixing locally. ended up using this docker env, extract the artifacts, works fine.

```
FROM ghcr.io/pragmatrix/rust-skia-linux:latest

# Prepare Rust toolchain
RUN rustup update && \
    rustup default stable && \
    rustup target add wasm32-unknown-emscripten

ENV EMCC_CFLAGS="-s ERROR_ON_UNDEFINED_SYMBOLS=0 -s MAX_WEBGL_VERSION=2 -s MODULARIZE=1 -s EXPORT_NAME=createRustSkiaModule -s EXPORTED_RUNTIME_METHODS=GL"

WORKDIR /rust-skia
COPY . /rust-skia

RUN source /emsdk/emsdk_env.sh && \
    cd wasm-example && \
    cargo build --release --target wasm32-unknown-emscripten

CMD ["bash"]
```

**Comment by softmarshmallow** [comment]
Update: I've managed to work on local env.

TL;DR ->

- have emsdk installed via git (as recommended) (I'm more carefully adding that as submodule to my repo, just to make things even strict - this is also how skia & canvaskit-wasm does it)
- [activate](https://github.com/gridaco/grida/blob/0f3c784f59847051033e9230739b1e5835759ce2/bin/activate-emsdk) that
  ```
  #!/usr/bin/env python3
  
  # Copyright 2022 Google LLC
  #
  # Use of this source code is governed by a BSD-style license that can be
  # found in the LICENSE file.
  
  import os
  import subprocess
  import sys
  import sysconfig
  
  EMSDK_ROOT = os.path.join('third_party', 'externals', 'emsdk')
  
  EMSDK_PATH = os.path.join(EMSDK_ROOT, 'emsdk.py')
  
  # This should match what's in //MODULE.bazel
  EMSDK_VERSION = '4.0.7'
  
  def main():
      if sysconfig.get_platform() in ['linux-aarch64', 'linux-arm64']:
          # This platform cannot install emsdk at the provided version. See
          # https://github.com/emscripten-core/emsdk/blob/main/emscripten-releases-tags.json#L5
          # for the latest version
          return
      try:
          subprocess.check_call([sys.executable, EMSDK_PATH, 'install', "--permanent", EMSDK_VERSION])
      except subprocess.CalledProcessError:
          print ('Failed to install emsdk')
          return 1
      try:
          subprocess.check_call([sys.executable, EMSDK_PATH, 'activate', "--permanent", EMSDK_VERSION])
      except subprocess.CalledProcessError:
          print ('Failed to activate emsdk')
          return 1
  
  
  if __name__ == '__main__':
    sys.exit(main())
  ```
- have [.cargo/config.toml](https://github.com/gridaco/grida/blob/0f3c784f59847051033e9230739b1e5835759ce2/crates/grida-canvas-wasm/.cargo/config.toml) (doesnt have to be, you can set EMCC_CFLAGS, that works too). 
  - Note: for latest emsdk, you need to set `EXPORTED_RUNTIME_METHODS` properly. it's changed ('HEAP32','HEAPU8','HEAPU16','HEAPU32','HEAPF32') see [FAQ](https://emscripten.org/docs/getting_started/FAQ.html)
  ```toml
  # Grida Canvas WASM Build Configuration
  # This file configures the build settings for the wasm32-unknown-emscripten target
  
  [target.wasm32-unknown-emscripten]
  # Use Emscripten's emcc as the linker for WebAssembly compilation
  linker = "emcc"
  
  # Linker arguments passed to Emscripten
  rustflags = [
      # Allow undefined symbols (useful for dynamic linking and Skia integration)
      "-C", "link-arg=-sERROR_ON_UNDEFINED_SYMBOLS=0",
      
      # Currently only targeting web (fs=false)
      # Target web environment (browser) instead of Node.js
      # We will be removing this once we figure out to make SSR/CSR not fail.
      "-C", "link-arg=-sENVIRONMENT=web",
      
      # Enable WebGL2 support for hardware-accelerated graphics
      "-C", "link-arg=-sMAX_WEBGL_VERSION=2",
      
      # Allow dynamic memory growth (important for large graphics operations)
      "-C", "link-arg=-sALLOW_MEMORY_GROWTH=1",
      
      # Create modular output (factory function instead of global Module)
      "-C", "link-arg=-sMODULARIZE=1",
      
      # Set the export function name for the modular output
      "-C", "link-arg=-sEXPORT_NAME=createGridaCanvas",
      
      # Export specific runtime methods for JavaScript access
      # GL: WebGL context access
      # UTF8 functions: String conversion utilities
      # HEAP functions: Direct memory access for performance-critical operations
      "-C", "link-arg=-sEXPORTED_RUNTIME_METHODS=['GL','lengthBytesUTF8','stringToUTF8','UTF8ToString','HEAP32','HEAPU8','HEAPU16','HEAPU32','HEAPF32']"
  ]
  
  ```
- source the env setup, set args, and run cargo build.
  ```
  third_party/externals/emsdk/emsdk_env.sh && \
          export CC=emcc && \
          export CXX=em++ && \
          export AR=emar && \
          time cargo build --release --target wasm32-unknown-emscripten
  ```


full version, ([justfile](https://github.com/gridaco/grida/blob/0f3c784f59847051033e9230739b1e5835759ce2/crates/grida-canvas-wasm/justfile))
```
# Grida Canvas WASM Build System
# Unified build system for all WASM build configurations

# Default recipe - shows available commands
default:
    @echo "🚀 Grida Canvas WASM Build System"
    @echo ""
    @echo "Available commands:"
    @echo "  just dev                - Development build (debug mode + copy + package)"
    @echo "  just build              - Production build (optimized + copy + package)"
    @echo "  just package            - Build package with pnpm"
    @echo "  just clean              - Clean all build artifacts"
    @echo "  just info               - Show build information"
    @echo ""
    @echo "Examples:"
    @echo "  just build                         # Production build (includes copy & package)"
    @echo "  just dev                           # Development build (includes copy & package)"
    @echo "  just clean && just build           # Clean and production build"

# Development build (debug mode)
dev:
    @just _build_wasm32_unknown_emscripten_debug
    @echo "📁 Copying debug WASM artifacts to lib/bin..."
    @mkdir -p lib/bin
    @cp ../../target/wasm32-unknown-emscripten/debug/*.js lib/bin/ 2>/dev/null || echo "No .js files found in debug"
    @cp ../../target/wasm32-unknown-emscripten/debug/*.wasm lib/bin/ 2>/dev/null || echo "No .wasm files found in debug"
    @echo "✅ Debug artifacts copied to lib/bin/"
    @just package

# Production build (optimized release)
build:
    @just _build_wasm32_unknown_emscripten_release
    @echo "📁 Copying release WASM artifacts to lib/bin..."
    @mkdir -p lib/bin
    @cp ../../target/wasm32-unknown-emscripten/release/*.js lib/bin/ 2>/dev/null || echo "No .js files found in release"
    @cp ../../target/wasm32-unknown-emscripten/release/*.wasm lib/bin/ 2>/dev/null || echo "No .wasm files found in release"
    @echo "✅ Release artifacts copied to lib/bin/"
    @just package

# Clean build artifacts
clean:
    @echo "🧹 Cleaning build artifacts..."
    cargo clean
    @echo "✅ Clean completed!"


# Build package with pnpm
package:
    @echo "📦 Building package with pnpm..."
    @pnpm --filter @grida/canvas-wasm build
    @echo "✅ Package build completed!"


# Show build information
info:
    @echo "📊 Grida Canvas WASM Build Information"
    @echo ""
    @echo "Build Scripts:"
    @echo "  Development: just dev             (~100MB, debug mode)"
    @echo "  Production:  just build           (~10MB, optimized)"
    @echo ""
    @echo "Output Locations:"
    @echo "  Development: ../../target/wasm32-unknown-emscripten/debug/deps/grida_canvas_wasm.wasm"
    @echo "  Production: ../../target/wasm32-unknown-emscripten/release/deps/grida_canvas_wasm.wasm"
    @echo ""
    @echo "Environment Requirements:"
    @echo "  - Emscripten SDK (emsdk)"
    @echo "  - Rust (latest stable)"
    @echo "  - Git (for submodules)"
    @echo ""
    @echo "Configuration:"
    @echo "  - Linker arguments configured in .cargo/config.toml"
    @echo "  - ERROR_ON_UNDEFINED_SYMBOLS=0 (allow undefined symbols)"
    @echo "  - ENVIRONMENT=web (web environment)"
    @echo "  - MAX_WEBGL_VERSION=2 (WebGL2 support)"
    @echo "  - ALLOW_MEMORY_GROWTH=1 (dynamic memory growth)"
    @echo "  - MODULARIZE=1 (modular output)"
    @echo "  - EXPORT_NAME=createGridaCanvas (export function name)"
    @echo "  - EXPORTED_RUNTIME_METHODS (GL, UTF8, HEAP functions)"

# Internal recipe: Build WASM (debug mode)
_build_wasm32_unknown_emscripten_debug:
    @echo "🔨 Building for wasm32-unknown-emscripten target..."
    @source ../../third_party/externals/emsdk/emsdk_env.sh && \
        export CC=emcc && \
        export CXX=em++ && \
        export AR=emar && \
        time cargo build --target wasm32-unknown-emscripten
    @echo "✅ Build completed successfully!"
    @echo "📁 Output file: ../../target/wasm32-unknown-emscripten/debug/grida_canvas_wasm.wasm"
    @echo "🎉 Grida Canvas WASM is ready for use!"

# Internal recipe: Build WASM (release mode)
_build_wasm32_unknown_emscripten_release:
    @echo "🔨 Building for wasm32-unknown-emscripten target (Production Mode)..."
    @source ../../third_party/externals/emsdk/emsdk_env.sh && \
        export CC=emcc && \
        export CXX=em++ && \
        export AR=emar && \
        time cargo build --release --target wasm32-unknown-emscripten
    @echo "✅ Production build completed successfully!"
    @echo "📁 Output file: ../../target/wasm32-unknown-emscripten/release/grida_canvas_wasm.wasm"
    @echo "⚡ Production optimizations applied:"
    @echo "   - Release mode compilation"
    @echo "   - O3 optimization level"
    @echo "   - Aggressive variable elimination"
    @echo "   - No debugging symbols"
    @echo "🎉 Grida Canvas WASM (Production) is ready!"
    @echo "💡 This build is optimized for production use"
    @echo "🚀 Use this for deployment and production applications"
```



To sum up,
1. have emsdk locally, via git
2. activate it
3. set env (you can permanently do this, but this example, we are just inlining it)
4. build. `cargo build wasm32-unknown-emscripten`


for wasm builders, I found it helpful exploring google/skia repo.
