### ISSUE TITLE
x86_64-unknown-linux-gnu download binary resource path 404

### ISSUE THREAD

**Issue by StringKe** [rust-skia/rust-skia#846]
```text
Caused by:
  process didn't exit successfully: `***/target/debug/build/skia-bindings-1b98c518282e36d8/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=DOCS_RS
  cargo:rerun-if-env-changed=SKIA_DEBUG
  HOST: x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=SKIA_SOURCE_DIR
  cargo:rerun-if-env-changed=FORCE_SKIA_BUILD
  cargo:rerun-if-env-changed=FORCE_SKIA_BINARIES_DOWNLOAD
  TRYING TO DOWNLOAD AND INSTALL SKIA BINARIES: 0.66.3/51577a9576c63d58a5fe-x86_64-unknown-linux-gnu-svg-textlayout
  cargo:rerun-if-env-changed=SKIA_BINARIES_URL
    FROM: https://github.com/rust-skia/skia-binaries/releases/download/0.66.3/skia-binaries-51577a9576c63d58a5fe-x86_64-unknown-linux-gnu-svg-textlayout.tar.gz
  DOWNLOAD AND INSTALL FAILED: https://github.com/rust-skia/skia-binaries/releases/download/0.66.3/skia-binaries-51577a9576c63d58a5fe-x86_64-unknown-linux-gnu-svg-textlayout.tar.gz: status code 404
  STARTING A FULL BUILD
  cargo:rerun-if-env-changed=CLANGCC
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=CLANGCXX
  cargo:rerun-if-env-changed=CXX
  HOST: x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=OPT_LEVEL
  cargo:rerun-if-env-changed=SKIA_USE_SYSTEM_LIBRARIES
  cargo:rerun-if-env-changed=SDKTARGETSYSROOT
  cargo:rerun-if-env-changed=SDKROOT
  HOST: x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=SKIA_NINJA_COMMAND
  cargo:rerun-if-env-changed=SKIA_GN_COMMAND
  Probing 'python'
  Probing 'python3'
  Python 3 found: "python3"
  Synchronizing Skia dependencies

  --- stderr
  Traceback (most recent call last):
    File "/home/chen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/skia-bindings-0.66.3/skia/tools/git-sync-deps", line 280, in <module>
      exit(main(sys.argv[1:]))
           ^^^^^^^^^^^^^^^^^^
    File "/home/chen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/skia-bindings-0.66.3/skia/tools/git-sync-deps", line 268, in main
      git_sync_deps(deps_file_path, argv, verbose)
    File "/home/chen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/skia-bindings-0.66.3/skia/tools/git-sync-deps", line 204, in git_sync_deps
      assert git
  AssertionError
  thread 'main' panicked at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/skia-bindings-0.66.3/build_support/skia/config.rs:263:9:
  `skia/tools/git-sync-deps` failed
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```toml
[package]
edition = "2021"
name = "***"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.12.2", default-features = false, features = ["napi8", "async", "full", "tokio_full", "error_anyhow", "deferred_trace", "serde_json"] }
napi-derive = "2.12.2"
skia-safe = { version = "0.66.3", features = ["svg"] }
serde = "1.0.188"
serde_json = "1.0.107"
tokio = { version = "1.32.0", features = ["full"] }
arc-swap = "1.6.0"
once_cell = "1.18.0"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
```
